# Generated by Django 5.0.1 on 2024-01-25 22:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorys",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
