# Generated by Django 5.0.1 on 2024-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_rename_categorys_category_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", max_length=25000, null=True),
        ),
    ]
