# Generated by Django 5.0.1 on 2024-01-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="fname",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="last_name",
            new_name="lname",
        ),
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
