# Generated by Django 5.0.1 on 2024-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_customer_fname_alter_customer_lname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="adresse",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
