# Generated by Django 5.0.1 on 2024-01-26 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_customer_adresse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="lname",
        ),
    ]
