# Generated by Django 5.0.1 on 2024-01-27 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_cart_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
    ]
