# Generated by Django 5.0.1 on 2024-01-27 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_cartitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
