# Generated by Django 5.0.1 on 2024-01-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_remove_order_items_delete_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="static/website/img/"),
        ),
    ]
