# Generated by Django 4.2.9 on 2024-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='livraisonStatus',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
