# Generated by Django 4.2.9 on 2024-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_livraisonstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='livraisonStatus',
            field=models.BooleanField(default=False),
        ),
    ]
