# Generated by Django 4.2.9 on 2024-02-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_order_livraisonstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='livraisonStatus',
        ),
    ]
