# Generated by Django 4.2.9 on 2024-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_livraisonstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='livraisonStatus',
            field=models.CharField(blank=True, default='not deivred', max_length=10),
        ),
    ]
