# Generated by Django 4.2.9 on 2024-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_order_livraisonstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='livraisonStatus',
            field=models.CharField(blank=True, default='encours', max_length=50),
        ),
    ]
